CREATE TABLE cliente(
   id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
   nombre      varchar        NOT NULL,
   celular  	varchar      	NOT NULL,
   direccion   varchar        NOT NULL,
   PRIMARY KEY (id)
);
