CREATE TABLE parametro(
   id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
   titulo varchar,
   valor  varchar        NOT NULL,
   tipo   varchar        NOT NULL,
   activo boolean,
   PRIMARY KEY (id)
);
